timeInterval: 60 # min
maxHistory: 200 # length

historyPath: "./uwu/history.txt"
reportPath: "./uwu/report.md"
promptPath: "./uwu/prompt.txt"

groqModel: "openai/gpt-oss-120b" # free

mainGuildId: "1059405085391728680"
mainChannelId: "1143954723758669835"
