name: hcc-eebot
version: 0.1.0.0
github: "paperee/hcc-eebot"
license: BSD-3-Clause
author: "paperee57(ee)"
maintainer: "admin@paperee.guru"
copyright: "2026 PAPEREE"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            application

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/paperee/hcc-eebot#readme>

dependencies:
  - base >= 4.7 && < 5
  - discord-haskell >= 1.18 && < 2.0
  - text >= 2.1
  - directory >= 1.3
  - bytestring >= 0.10
  - time >= 1.12
  - yaml >= 0.11
  - req >= 3.13
  - aeson >= 2.2.4
  - vector >= 0.12

ghc-options:
  - -O0
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fno-warn-unused-imports
  - -fno-warn-redundant-constraints
  - -fexternal-interpreter
  - -fdiagnostics-as-json

library:
  source-dirs: src

executables:
  hcc-eebot-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hcc-eebot

tests:
  hcc-eebot-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hcc-eebot
